### ISSUE TITLE
Setup express backend app in monorepo

### ISSUE THREAD

**Issue by ringale95** [be-chef/chef-workspace#14]
### **Acceptance Criteria:**

Set up an Express backend application in the Nx monorepo to handle backend API services. 

---

### **Steps to Complete:**
1. Install the Nx Express plugin to enable Express application generation.
   ```bash
   npm i @nx/express
   ```

2. Generate a new Express application named `chef-express` in the `apps/` folder.
   ```bash
   nx generate @nx/express:application apps/chef-express
   ```

3. Verify that the necessary boilerplate files (e.g., `main.ts`) and configurations were created by Nx:
   - Confirm the app structure is created in `apps/chef-express`.
   
4. Test the new Express app by running it locally:
   ```bash
   nx serve chef-express
   ```
   - Ensure the app runs without errors.
   - Verify that the server is accessible on `http://localhost:[default-port]`.

**Comment by ringale95** [comment]
@andytambe31 @PS8924 please review this story. Here is the PR: https://github.com/be-chef/chef-workspace/pull/12

**Comment by andytambe31** [comment]
LGTM

**Comment by PS8924** [comment]
LGTM
